# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = 'gray'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#083c4a'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = 'gray'

# List of user stylesheet filenames to use.
# Type: List of File, or File
c.content.user_stylesheets = []

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = 'white'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#002b36'

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
config.bind('D', 'close')
config.bind('\\n', 'config-cycle content.user_stylesheets ~/Themes/solarized-everything-css/css/solarized-dark/solarized-dark-all-sites.css "" ;; reload')
config.bind('close', 'D')
