#!/usr/bin/env bash

#update your system
sudo apt update && sudo apt upgrade -y

# get a .deb package installer
sudo apt install gdebi -y

# make copying from files & command line convenient
sudo apt install xclip -y

#various dev tools
sudo apt install software-properties-common software-properties-gtk \
    python-software-properties git vim-nox tmux zsh python3 \
    default-jdk -y

#vs code
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https -y
sudo apt update
sudo apt install code -y

#Csharp
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt install -y apt-transport-https
sudo apt update
sudo apt install -y dotnet-sdk-2.1
sudo apt install mono-devel -y

#pip3
curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6

#neofetch for show-offsies
sudo apt install -y neofetch

#config git
git config --global user.name "OxSon"
git config --global user.email "al3cmills@gmail.com"
# get an ssh key & such
ssh-keygen -t rsa -b 4096 -C "al3cmills@gmail.com" -f "$HOME/.ssh/id_rsa" -q
eval "$(ssh-agent -s)"
echo "remember to add key to github here:  https://github.com/settings/keys"

# get vimrc & bash rc and such
cd
git clone git@github.com:A-L-M/dotfiles.git

# get npm and nodejs
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash - 
sudo apt update && sudo apt install -y nodejs

# clean simplified man pages
sudo npm install -g tldr --allow-root --unsafe-perm=true
tldr --update

# get redshift; your eyes will
# thank you. 
sudo apt install -y redshift
echo "Remember to add redshift to system startup!"

#best browser
sudo apt install -y qutebrowser
#for <C-e> purposes with qutebrowser
sudo apt install vim-gtk3
# also get firefox for netflix purposes
sudo apt install firefox -y

#solarized-dark all the things
cd
mkdir Themes && cd Themes
git clone git@github.com:jkaving/intellij-colors-solarized.git  #intellij
sudo rm -r intellij-colors-solarized/.git intellij-colors-solarized/.gitignore
git clone git@github.com:altercation/vim-colors-solarized.git   #vim
sudo rm -r vim-colors-solarized/.git vim-colors-solarized/.gitignore
git clone git@github.com:braver/vscode-solarized.git            #vscode
sudo rm -r vscode-colors-solarized/.git vscode-colors-solarized/.gitignore
#set pantehon terminal to Solarized Dark
echo "This script sets the pantheon terminal to the Solarized theme."
 
base0='#838394949696'
base1='#9393a1a1a1a1'
base3='#fdfdf6f6e3e3'
base00='#65657b7b8383'
base01='#58586e6e7575'
base03='#00002B2B3636'
solarized_palette='#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3'
default_palette='#303030:#e1321a:#6ab017:#ffc005:#004f9e:#ec0048:#2aa7e7:#f2f2f2:#5d5d5d:#ff361e:#7bc91f:#ffd00a:#0071ff:#ff1d62:#4bb8fd:#a020f0'
 
gsettings set org.pantheon.terminal.settings background $base03
gsettings set org.pantheon.terminal.settings foreground $base0
gsettings set org.pantheon.terminal.settings cursor-color $base0
gsettings set org.pantheon.terminal.settings palette $solarized_palette

# various other software
sudo apt install libreoffice -y
sudo apt install vlc -y
sudo apt install deja-dup -y
sudo apt install mpv -y

#laptop settings below here:
########################### SOMETHING HERE IS BROKEN!!!!!!!!
# TLP helps w/ laptop overheating // maybe this?
# sudo apt install tlp tlp-rdw
# osX-like gestures
# sudo apt install xdotool wmctrl// maybe this?
# sudo apt install libinput-tools// maybe this?
# git clone http://github.com/bulletmark/libinput-gestures
# cd libinput-gestures
# sudo make install
# swap caps:ctrl and disable
# natural scrolling
# in system settings
